// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYaPfjK90mWyuv52Nrh8OtQkD3oHXQ6Ks',
    appId: '1:457050981945:web:4e92372acab51e3d70afe8',
    messagingSenderId: '457050981945',
    projectId: 'checkin-app-31ea8',
    authDomain: 'checkin-app-31ea8.firebaseapp.com',
    storageBucket: 'checkin-app-31ea8.appspot.com',
    measurementId: 'G-EQ59N1QF12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeicrk9CrCqZJR5ebOAsbR_HSKxk3pWTc',
    appId: '1:457050981945:android:496060b3cece4f4770afe8',
    messagingSenderId: '457050981945',
    projectId: 'checkin-app-31ea8',
    storageBucket: 'checkin-app-31ea8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKlZoGI-w5PbKGrWio8rAIg9q5wWhLj5M',
    appId: '1:457050981945:ios:4bc3434cefa396a270afe8',
    messagingSenderId: '457050981945',
    projectId: 'checkin-app-31ea8',
    storageBucket: 'checkin-app-31ea8.appspot.com',
    androidClientId: '457050981945-uimhsfrg7tjn85794vu25tr6opfa1fmm.apps.googleusercontent.com',
    iosClientId: '457050981945-ud6a468rdk6v8n7g9moas6iksma5021r.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKlZoGI-w5PbKGrWio8rAIg9q5wWhLj5M',
    appId: '1:457050981945:ios:a15a66f2e054307970afe8',
    messagingSenderId: '457050981945',
    projectId: 'checkin-app-31ea8',
    storageBucket: 'checkin-app-31ea8.appspot.com',
    androidClientId: '457050981945-uimhsfrg7tjn85794vu25tr6opfa1fmm.apps.googleusercontent.com',
    iosClientId: '457050981945-bi9ivs2974cjvagd3ugu354lgbq2l3kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
